REM обновить файлы стоек и подпрограмм дистрибутива
COPY C:\development\NCMEnv\Def\2C42Demo.sm3
COPY C:\development\NCMEnv\Def\Acramatic.sm3
COPY C:\development\NCMEnv\Def\DMT_Fanuc18iTB.sm3
COPY C:\development\NCMEnv\Def\FanMTDemo2Chusk.sm3
COPY C:\development\NCMEnv\Def\Fanuc0-TB-TT.sm3
COPY C:\development\NCMEnv\Def\FANUC6M_V1.sm3
COPY C:\development\NCMEnv\Def\FanucDemo.sm3
COPY C:\development\NCMEnv\Def\FanucDemo2.sm3
COPY C:\development\NCMEnv\Def\FikusDemoMT.sm3
COPY C:\development\NCMEnv\Def\G7_SPATIAL2.h
COPY C:\development\NCMEnv\Def\HAAS-SL.sm3
COPY C:\development\NCMEnv\Def\Haas.sm3
COPY C:\development\NCMEnv\Def\ISO.sm3
COPY C:\development\NCMEnv\Def\L3030.sm2
COPY C:\development\NCMEnv\Def\Lathe_CNC_3.sm2
COPY C:\development\NCMEnv\Def\N33.SM3
COPY C:\development\NCMEnv\Def\NC-110_lathe.sm3
COPY C:\development\NCMEnv\Def\NCM_BaltSys_Mill.sm3
COPY C:\development\NCMEnv\Def\NCM_BaltSys_Turn.sm3
COPY C:\development\NCMEnv\Def\NCM_FANUC_MILL.sm3
COPY C:\development\NCMEnv\Def\NCM_FANUC_MillTurn.sm3
COPY C:\development\NCMEnv\Def\NCM_FANUC_C_MillTurn.sm3
COPY C:\development\NCMEnv\Def\NCM_HAAS_MILLTURN.sm3
COPY C:\development\NCMEnv\Def\NCM_HEIDENHAIN_MILL.sm3
COPY C:\development\NCMEnv\Def\NCM_NC31_TURN.sm3
COPY C:\development\NCMEnv\Def\NCM_SIEMENS_840D_MILL.sm3
COPY C:\development\NCMEnv\Def\NCM_SIEMENS_840D_MILLTURN.sm3
COPY C:\development\NCMEnv\Def\SIN840-DT-MACH1512.sm2
COPY C:\development\NCMEnv\Def\Sin840Mill.SPF
COPY C:\development\NCMEnv\Def\SubProgrMT.nc
COPY C:\development\NCMEnv\Def\SubProgrFanucMT.nc
COPY C:\development\NCMEnv\Def\ToolChange_1.sub
COPY C:\development\NCMEnv\Def\ToolChange_2.sub
COPY C:\development\NCMEnv\Def\TRAUB.sm3
