//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NCMControlRus.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ERROR_IMAGE_LOAD            101
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_NCEditor2TYPE               130
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_TREE_TB_PRES                 144
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_HELP_PANE                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDB_MENU_IMAGES_24              180
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define IDS_SETUP_FAULT                 200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_TREE_CMENU                  311
#define IDD_ADD_WREPL                   312
#define IDD_SELECT_XML                  313
#define IDS_ERROR_XML_PROTO             316
#define IDS_BOOL_YES                    400
#define IDS_BOOL_NO                     401
#define IDS_EMPTY                       402
#define IDS_ERROR_FILE                  403
#define IDS_ERROR_XML                   404
#define IDS_WORD_REPLACEMENT            405
#define IDS_ERROR_MOVE_WREPL            406
#define IDS_UNKNOWN_DEFINITION          407
#define IDS_WREPL_ELEMENT_HELP          408
#define IDS_WREPL_ELEMENT_PICTURE       409
#define IDS_ERROR_GROUP_DOESNTEXIST     410
#define IDS_ERROR_UNKNOWN_TYPE          411
#define IDS_ERROR_XML_NAME_ELEMENT      412
#define IDS_ERROR_XML_ENUM_WITHOUT_VARIANTS 413
#define IDS_ERROR_XML_ENUM_WRONG_VARIANTS 414
#define IDS_ERROR_XML_GROUP_NAME        415
#define IDS_ERROR_XML_UNKNOWN_ELEMENT   416
#define IDS_ERROR_PARSER_BACKSLASH_EXPECTED 417
#define IDS_ERROR_PARSER_LESS_2STRINGS  418
#define IDS_ERROR_PARSER_NO_BEGIN_SIGNATURE 419
#define IDS_ERROR_PARSER_UNEXPECTED_END 420
#define IDS_ERROR_PARSER_BLANK_LINE_EXPECTED 421
#define IDS_ERROR_PARSER_DEFINITION     422
#define IDS_ERROR_PARSER_WREPL          423
#define IDS_ERROR_PARSER_SECTION_ADD    424
#define IDS_ERROR_PARSER_SECTION_NAME_EXPECTED 425
#define IDS_MESSAGE_DOESNT_DEFINED      426
#define IDS_ERROR_PICTURE_LOADING       427
#define IDS_GROUP                       428
#define IDS_SECTION_NAME                429
#define IDS_DEFINITION_LIST             430
#define IDS_REPLACE                     431
#define IDS_SOURCE_STRING               432
#define IDS_DESTINATION_STRING          433
#define IDS_GROUP_NAME                  434
#define IDS_DEFINITION_WORD             435
#define IDS_DEFAULT                     436
#define IDS_PRESENCE                    437
#define IDS_TYPEW_BOOL                  500
#define IDS_TYPEW_INT                   501
#define IDS_TYPEW_DOUBLE                502
#define IDS_TYPEW_STRING                503
#define IDS_TYPEW_EENUM                 504
#define IDS_TYPEW_SENUM                 505
#define IDS_WREPL_ADD_EMPTY             600
#define IDS_WREPL_ADD_EXISTS            601
#define IDS_DEFAULT_PICTURE             700
#define IDS_PROP_TOOLBAR_TOOLTIP0       800
#define IDS_PROP_TOOLBAR_TOOLTIP1       801
#define IDS_PROP_TOOLBAR_TOOLTIP2       802
#define IDS_PROP_TOOLBAR_TOOLTIP3       803
#define IDS_PROP_TOOLBAR_TOOLTIP4       804
#define IDS_TREE_TOOLBAR_TOOLTIP0       805
#define IDS_TREE_TOOLBAR_TOOLTIP1       806
#define IDS_TREE_TOOLBAR_TOOLTIP2       807
#define IDS_TREE_TOOLBAR_TOOLTIP3       808
#define IDS_TREE_TOOLBAR_TOOLTIP4       809
#define IDC_EDIT3                       1003
#define IDC_EDIT4                       1004
#define IDC_LIST1                       1005
#define IDC_XML_NAME                    1005
#define ID_EDIT_UNDO32781               32781
#define ID_EDIT_REDO32782               32782
#define ID_EDIT_UNDO32783               32783
#define ID_EDIT_UNDO1                   32784
#define ID_EDIT_REDO1                   32787
#define ID_EDIT_REDO32788               32788
#define ID_MENU_SOME                    32789
#define ID_MENU_MENU                    32790
#define ID_MENU_ITEMS                   32791
#define ID_TREE_TB_ABC                  32792
#define ID_TREE_TB_GROUP                32793
#define ID_TREE_TB_EXPAND               32794
#define ID_ADD_WREPL                    32795
#define ID_DEL_WREPL                    32796
#define ID_KKKK_KKK                     32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
