 
// Commands (ID_* and IDM_*) 
#define HID_LIST_REPDLG_REPS                    0x107FC
#define HID_PAUSE_NUM                           0x113C4
#define HID_SETTINGS_SAVE                       0x18001
#define HID_SAVE                                0x18004
#define HID_POPUP                               0x18005
#define HID_DELETE                              0x18007
#define HID_CH_PROGR_VIEW                       0x18008
#define HID_CH_PROGR_VISIBLE                    0x1800A
#define HID_CH_PROGR_TEXT                       0x1800B
#define HID_LOAD                                0x1800C
#define HID_POPUP_MAX                           0x1800D
#define HID_CH_PROGRAM_COLOR                    0x18019
#define HID_SETTINGS_UNIT                       0x1801A
#define HID_VIEW                                0x1801D
#define HID_VIEW_WFRAME                         0x1801E
#define HID_VIEW_SHADE                          0x1801F
#define HID_PA_TOOLS_LOAD                       0x18020
#define HID_PA_TOOLS_CR                         0x18021
#define HID_CH_TOOL_DELETE                      0x18023
#define HID_CH_TOOL_COLOR                       0x18024
#define HID_PA_STOCK_CR                         0x18029
#define HID_VIEW_AXES                           0x1802B
#define HID_TB_SIMUL                            0x1802C
#define HID_TB_GENER                            0x1802D
#define HID_RUN_STEP                            0x18030
#define HID_PA_PROG_SHOW                        0x18034
#define HID_STEP_FOR                            0x18035
#define HID_STEP_BACK                           0x18036
#define HID_STEP_END                            0x18037
#define HID_STEP_RUN                            0x18039
#define HID_STEP_HERE                           0x1803A
#define HID_STEP_BEGIN                          0x1803C
#define HID_CH_TOOL_EDIT                        0x1803E
#define HID_NCUNIT_LOAD                         0x1803F
#define HID_EDIT                                0x18041
#define HID_EDIT_UPDATE                         0x18042
#define HID_EDIT_RESTORE                        0x18044
#define HID_EDIT_PREVIEW                        0x18045
#define HID_PA_STOCK_COLOR                      0x18046
#define HID_PA_STOCK_VISIBLE                    0x18047
#define HID_PA_STOCK_DELETE                     0x18048
#define HID_PA_STOCK_LOAD                       0x18049
#define HID_STEP_JUMP                           0x18060
#define HID_TB                                  0x18062
#define HID_CH_TOOL_VISIBLE                     0x18069
#define HID_TB_SIM_REDRAW                       0x18070
#define HID_TB_SIM_SECT_X                       0x18071
#define HID_TB_SIM_SECT_SCREEN                  0x18072
#define HID_TB_SIM_SECT_Z                       0x18073
#define HID_TB_SIM_SECT_3                       0x18074
#define HID_TB_SIM_SECT_Y                       0x18075
#define HID_JUMP_END                            0x1807F
#define HID_PA_STOCK_CR_CYL                     0x18081
#define HID_NCUNIT_START                        0x18083
#define HID_PA_STOCK_CR_BOX                     0x18088
#define HID_OGL_CONFIG                          0x18089
#define HID_PA_STOCK_WF                         0x1808B
#define HID_PA_TOOLS_ALLVIS                     0x1808C
#define HID_PA_TOOLS_ALLUNV                     0x1808D
#define HID_PA_TOOLS_INV                        0x1808E
#define HID_PA_PROG_ALLVIS                      0x1808F
#define HID_PA_PROG_ALLUNV                      0x18090
#define HID_PA_PROG_INV                         0x18091
#define HID_PA_STOCK_TRANSP                     0x18095
#define HID_CH_TOOL_WF                          0x18096
#define HID_CH_TOOL_TRANSP                      0x18097
#define HID_CH_PROGR_ACTIVE                     0x18098
#define HID_HIDE_ITEM                           0x18099
#define HID_SETTINGS                            0x1809B
#define HID_STEP_ERROR                          0x1809C
#define HID_JUMP_NUM                            0x1809E
#define HID_SETTINGS_APPEARANCE                 0x180A0
#define HID_SETTINGS_CONTROL_PANEL              0x180A1
#define HID_SETTINGS_GRAPHICS                   0x180A2
#define HID_STEP_TOOL                           0x180A3
#define HID_STATE_VIEW_SETTINGS                 0x180A4
#define HID_MODE_PAINTER                        0x180E8
#define HID_DISP_EXECUTE                        0x180E9
#define HID_FIND_TEXT                           0x180EA
#define HID_ADD_BOOKMARK                        0x180EB
#define HID_NEXT_BOOKMARK                       0x180EC
#define HID_PREV_BOOKMARK                       0x180ED
#define HID_CLEARALL_BOOKMARK                   0x180EE
#define HID_PA_PROG_COMP                        0x184D0
#define HID_PA_PROG_PROG                        0x184D1
#define HID_VIEW_REGEN                          0x184D3
#define HID_TB_SIM_MAGNIFY                      0x184D6
#define HID_FILE_EXPORT                         0x184D7
#define HID_STEP_TIMER                          0x184D8
#define HID_PA_PROGR_CR                         0x184DA
#define HID_NOTES                               0x184DC
#define HID_PA_PROG_PART                        0x184E1
#define HID_PA_PROG_RELO                        0x184E2
#define HID_REGISTRATION                        0x184E3
#define HID_CH_TOOL_PASCOLOR                    0x184E4
#define HID_VIEW_OUTLINE                        0x184E5
#define HID_CALC_TIME                           0x184E6
#define HID_CALC_VOLUME                         0x184E8
#define HID_CH_TOOL_CUT                         0x184EA
#define HID_CH_TOOL_COPY                        0x184EB
#define HID_CH_TOOL_PASTE                       0x184EC
#define HID_VOLUME_ON                           0x184EC
#define HID_PA_STOCK_CR_STL                     0x184EE
#define HID_REPORTS_SELECT                      0x184EF
#define HID_CH_PROGR_DXFExport                  0x184F0
#define HID_CALC_GEOM                           0x184F1
#define HID_VIEW_TOOLBAR_NTEXT                  0x184F3
#define HID_VIEW_TOOLBAR_STEP                   0x184F4
#define HID_VIEW_TOOLBAR_STEP1                  0x184F5
#define HID_REPORTS_EDIT                        0x184F6
#define HID_REPORTS_ACTIVATE                    0x184F7
#define HID_REPORTS_PAUSE                       0x184F8
#define HID_CH_PROGR_Comment                    0x184F9
#define HID_CH_PROGR_APTexport                  0x184FA
#define HID_PA_TOOLS_OP                         0x184FB
#define HID_VIEW_DYN                            0x184FD
#define HID_PA_PROG_WORM                        0x184FF
#define HID_PA_PROG_FULL                        0x18500
#define HID_PA_TOOLS_USE                        0x18501
#define HID_PA_TOOLS_SHAPE                      0x18502
#define HID_VOLUME_TREE                         0x18503
#define HID_VIEW_TR_GEOM                        0x18504
#define HID_TEXT_SCROLL                         0x18505
#define HID_TEXT_SELCURCADR                     0x18506
#define HID_TEXT_SELERROR                       0x18507
#define HID_TEXT_NOTPAINT                       0x18508
#define HID_EDIT_RENUM                          0x18509
#define HID_TB_SIM_EDGES                        0x1850D
#define HID_LANGUAGE_ENGLISH                    0x1850F
#define HID_LANGUAGE_RUSSIAN                    0x18510
#define HID_LANGUAGE_DEFAULT                    0x18511
#define HID_MENU_REPORTS_CLEAR                  0x18512
#define HID_MENU_REPORTS_VIEW                   0x18513
#define HID_MENU_REPORTS_SELECT                 0x18514
#define HID_STOCK_EXP                           0x1851D
#define HID_STOCK_IMP                           0x1851E
#define HID_PA_MACH_LOAD                        0x18522
#define HID_PA_MACH_VISIBLE                     0x18523
#define HID_DEBUGMODE                           0x18524
#define HID_STOCK_EXSTL                         0x18527
#define HID_PA_PART_CR_STL                      0x18528
#define HID_PA_PART_DELETE                      0x18529
#define HID_PA_PART_COLOR                       0x1852A
#define HID_PA_PART_VISIBLE                     0x1852B
#define HID_PA_PART_WF                          0x1852C
#define HID_PA_PART_TRANSP                      0x1852D
#define HID_VIEW_SECTION                        0x1852F
#define HID_WIN_STOCK                           0x18539
#define HID_WIN_MACH                            0x1853A
#define HID_WIN_STOCK_P                         0x1853C
#define HID_WIN_MACH_P                          0x1853D
#define HID_WIN_HOR                             0x1853E
#define HID_WIN_VERT                            0x1853F
#define HID_MEASURE                             0x18541
#define HID_WIRE_MODE                           0x18542
#define HID_STEP_STOP                           0x18543
#define HID_SMOTHNESS_MODE                      0x18546
#define HID_QUICKLY_MODE                        0x18547
#define HID_ANIMATE_STOP                        0x18548
#define HID_BREAKPOINT_TABLE                    0x18549
#define HID_EXECUTE_CURRENT                     0x1854A
#define HID_RUN_TO_BREAKPOINT                   0x1854B
#define HID_ANIMATE_PAUSE                       0x1854C
#define HID_RESET                               0x1854D
#define HID_BREAKPOINT_BACK                     0x1854E
#define HID_BREAKPOINT_ONWARD                   0x1854F
#define HID_BREAKPOINT_FORWARD                  0x18550
#define HID_PAUSE_BACK                          0x18551
#define HID_PAUSE_FORWARD                       0x18552
#define HID_RESULT_MODE                         0x18555
#define HID_STOCK_INIT                          0x1855D
#define HID_BUTTON34150                         0x18566
#define HID_BP1                                 0x18566
#define HID_BUTTON34151                         0x18567
#define HID_BP2                                 0x18567
#define HID_BUTTON34152                         0x18568
#define HID_BP3                                 0x18568
#define HID_BUTTON34153                         0x18569
#define HID_BP4                                 0x18569
#define HID_BUTTON34154                         0x1856A
#define HID_VIEW_VIEW                           0x18570
#define HID_Menu                                0x18571
#define HID_VIEW_SIMULATE                       0x18572
#define HID_VIEW_BREAKPOINT                     0x18574
#define HID_VIEW_TOOLS                          0x18576
#define HID_VIEW_PANEL                          0x18579
#define HID_VIEW_NUMBER                         0x1857A
#define HID_TEXT_DOWN                           0x18581
#define HID_TREE_ON_OFF                         0x18582
#define HID_TEXT_ON_OFF                         0x18583
#define HID_VIEW_STEPFORBACK                    0x18586
#define HID_VIEW_MODES                          0x18587
#define HID_EDITOR_STATUSBAR                    0x18588
#define HID_VIEW_DEFAULT                        0x1858A
#define HID_VIEW_NAVIGATION                     0x1858C
#define HID_VIEW_TEXT                           0x1858D
#define HID_STOCK_TRANSP                        0x1858F
#define HID_PA_STOCK_EDGE                       0x18591
#define HID_VIEW_SIZE_ICON                      0x18593
#define HID_BUTTON_LINENUM                      0x18595
#define HID_BUTTON_ADDSPACE                     0x18597
#define HID_BUTTON_REMOVESPACE                  0x18598
#define HID_COMPARISON                          0x1859B
#define HID_CHECK_MI                            0x1859D
 
// Prompts (IDP_*) 
#define HIDP_OLE_INIT_FAILED                    0x30064
#define HIDP_FAILED_TO_CREATE                   0x30066
#define HIDP_FAILED_TO_CREATE2                  0x30067
 
// Resources (IDR_*) 
#define HIDR_CNTR_INPLACE                       0x20006
#define HIDR_STEP_NUM                           0x2007F
#define HIDR_MAINFRAME                          0x20080
#define HIDR_CH_TOOL                            0x20082
#define HIDR_PA_PROGR                           0x20084
#define HIDR_TEXT_EDIT                          0x20085
#define HIDR_CONT_MENU                          0x20086
#define HIDR_PA_TOOLS                           0x20087
#define HIDR_CH_PROGR                           0x2008A
#define HIDR_PA_STOCK                           0x2008D
#define HIDR_PA_UNIT                            0x20094
#define HIDR_STATE_VIEW_NOITEM                  0x200A0
#define HIDR_STATE_VIEW_ITEM                    0x200A1
#define HIDR_CH_TOOL1                           0x200A2
#define HIDR_STEP_NUM1                          0x200A3
#define HIDR_MENU1                              0x20124
#define HIDR_TEXT_EDIT_DOWN                     0x20127
#define HIDR_PA_MACH                            0x20128
#define HIDR_PA_PART                            0x20129
 
// Dialogs (IDD_*) 
#define HIDD_ABOUTBOX                           0x20072
#define HIDD_STOCK_CREATE_CYL                   0x20091
#define HIDD_STOCK_CREATE_BOX                   0x20092
#define HIDD_TRANSP                             0x20098
#define HIDD_GRAPHICS_SETTINGS                  0x2009B
#define HIDD_STATE_SETTINGS                     0x200A4
#define HIDD_APPEARANCE_SETTINGS                0x200A5
#define HIDD_MODE_PAINTER                       0x200D1
#define HIDD_REGISTRATION                       0x200E0
#define HIDD_MESSAGE                            0x200EE
#define HIDD_STOCK_CREATE_STL                   0x200F3
#define HIDD_COMMENT                            0x200F5
#define HIDD_MARKERS                            0x20120
#define HIDD_FONTS                              0x20121
#define HIDD_TRANSP_GEOM                        0x20125
#define HIDD_OGL_INIT                           0x20126
#define HIDD_EDIT_RENUM                         0x20129
#define HIDD_SECURITY                           0x2012A
#define HIDD_REP_REP_EDITOR                     0x2012C
#define HIDD_TEXT_ERR                           0x2012E
#define HIDD_REP_ACTIVEREP                      0x2012F
#define HIDD_DIALOG_REDPORTVIEW                 0x20130
#define HIDD_DIALOG1                            0x20131
#define HIDD_PAUSE                              0x20133
#define HIDD_QUICK_STEP                         0x20134
#define HIDD_STOCK_TRANSP                       0x2016A
 
// Frame Controls (IDW_*) 
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

// Non-Client HitTest help IDs
#define HID_HT_NOWHERE                          0x40000
#define HID_HT_CAPTION                          0x40002
#define HID_HT_SIZE                             0x40004
#define HID_HT_HSCROLL                          0x40006
#define HID_HT_VSCROLL                          0x40007
#define HID_HT_MINBUTTON                        0x40008
#define HID_HT_MAXBUTTON                        0x40009
#define HID_HT_SIZE                             0x4000A // alias: ID_HT_LEFT
#define HID_HT_SIZE                             0x4000B // alias: ID_HT_RIGHT
#define HID_HT_SIZE                             0x4000C // alias: ID_HT_TOP
#define HID_HT_SIZE                             0x4000D // alias: ID_HT_TOPLEFT
#define HID_HT_SIZE                             0x4000E // alias: ID_HT_TOPRIGHT
#define HID_HT_SIZE                             0x4000F // alias: ID_HT_BOTTOM
#define HID_HT_SIZE                             0x40010 // alias: ID_HT_BOTTOMLEFT
#define HID_HT_SIZE                             0x40011 // alias: ID_HT_BOTTOMRIGHT
#define HID_HT_SIZE                             0x40012 // alias: ID_HT_BORDER
#define HID_HT_OBJECT							0x40013
#define HID_HT_CLOSE							0x40014
#define HID_HT_HELP								0x40015

// WM_SYSCOMMAND help IDs
#define HID_SC_SIZE                             0x1EF00
#define HID_SC_MOVE                             0x1EF01
#define HID_SC_MINIMIZE                         0x1EF02
#define HID_SC_MAXIMIZE                         0x1EF03
#define HID_SC_NEXTWINDOW                       0x1EF04
#define HID_SC_PREVWINDOW                       0x1EF05
#define HID_SC_CLOSE                            0x1EF06
#define HID_SC_RESTORE                          0x1EF12
#define HID_SC_TASKLIST                         0x1EF13

// File MRU and aliases
#define HID_FILE_MRU_FILE1                      0x1E110
#define HID_FILE_MRU_FILE1                      0x1E111 // aliases: MRU_2 - MRU_16
#define HID_FILE_MRU_FILE1                      0x1E112
#define HID_FILE_MRU_FILE1                      0x1E113
#define HID_FILE_MRU_FILE1                      0x1E114
#define HID_FILE_MRU_FILE1                      0x1E115
#define HID_FILE_MRU_FILE1                      0x1E116
#define HID_FILE_MRU_FILE1                      0x1E117
#define HID_FILE_MRU_FILE1                      0x1E118
#define HID_FILE_MRU_FILE1                      0x1E119
#define HID_FILE_MRU_FILE1                      0x1E11A
#define HID_FILE_MRU_FILE1                      0x1E11B
#define HID_FILE_MRU_FILE1                      0x1E11C
#define HID_FILE_MRU_FILE1                      0x1E11D
#define HID_FILE_MRU_FILE1                      0x1E11E
#define HID_FILE_MRU_FILE1                      0x1E11F

// Window menu list
#define HID_WINDOW_ALL                          0x1EF1F

// OLE menu and aliases
#define HID_OLE_VERB_1                          0x1E210
#define HID_OLE_VERB_1                          0x1E211 // aliases: VERB_2 -> VERB_16
#define HID_OLE_VERB_1                          0x1E212
#define HID_OLE_VERB_1                          0x1E213
#define HID_OLE_VERB_1                          0x1E214
#define HID_OLE_VERB_1                          0x1E215
#define HID_OLE_VERB_1                          0x1E216
#define HID_OLE_VERB_1                          0x1E217
#define HID_OLE_VERB_1                          0x1E218
#define HID_OLE_VERB_1                          0x1E219
#define HID_OLE_VERB_1                          0x1E21A
#define HID_OLE_VERB_1                          0x1E21B
#define HID_OLE_VERB_1                          0x1E21C
#define HID_OLE_VERB_1                          0x1E21D
#define HID_OLE_VERB_1                          0x1E21E
#define HID_OLE_VERB_1                          0x1E21F

// Commands (HID_*) 
#define HID_FILE_NEW                            0x1E100
#define HID_FILE_OPEN                           0x1E101
#define HID_FILE_CLOSE                          0x1E102
#define HID_FILE_SAVE                           0x1E103
#define HID_FILE_SAVE_AS                        0x1E104
#define HID_FILE_PAGE_SETUP                     0x1E105
#define HID_FILE_PRINT_SETUP                    0x1E106
#define HID_FILE_PRINT                          0x1E107
#define HID_FILE_PRINT_DIRECT                   0x1E108
#define HID_FILE_PRINT_PREVIEW                  0x1E109
#define HID_FILE_UPDATE                         0x1E10A
#define HID_FILE_SAVE_COPY_AS                   0x1E10B
#define HID_FILE_SEND_MAIL                      0x1E10C
#define HID_EDIT_CLEAR                          0x1E120
#define HID_EDIT_CLEAR_ALL                      0x1E121
#define HID_EDIT_COPY                           0x1E122
#define HID_EDIT_CUT                            0x1E123
#define HID_EDIT_FIND                           0x1E124
#define HID_EDIT_PASTE                          0x1E125
#define HID_EDIT_PASTE_LINK                     0x1E126
#define HID_EDIT_PASTE_SPECIAL                  0x1E127
#define HID_EDIT_REPEAT                         0x1E128
#define HID_EDIT_REPLACE                        0x1E129
#define HID_EDIT_SELECT_ALL                     0x1E12A
#define HID_EDIT_UNDO                           0x1E12B
#define HID_EDIT_REDO                           0x1E12C
#define HID_WINDOW_NEW                          0x1E130
#define HID_WINDOW_ARRANGE                      0x1E131
#define HID_WINDOW_CASCADE                      0x1E132
#define HID_WINDOW_TILE_HORZ                    0x1E133
#define HID_WINDOW_TILE_VERT                    0x1E134
#define HID_WINDOW_SPLIT                        0x1E135
#define HID_APP_ABOUT                           0x1E140
#define HID_APP_EXIT                            0x1E141
#define HID_HELP_INDEX                          0x1E142
#define HID_HELP_FINDER                         0x1E143
#define HID_HELP_USING                          0x1E144
#define HID_CONTEXT_HELP                        0x1E145
#define HID_NEXT_PANE                           0x1E150
#define HID_PREV_PANE                           0x1E151
#define HID_FORMAT_FONT                         0x1E160
#define HID_OLE_INSERT_NEW                      0x1E200
#define HID_OLE_EDIT_LINKS                      0x1E201
#define HID_OLE_EDIT_CONVERT                    0x1E202
#define HID_OLE_EDIT_CHANGE_ICON                0x1E203
#define HID_OLE_EDIT_PROPERTIES                 0x1E204
#define HID_VIEW_TOOLBAR                        0x1E800
#define HID_VIEW_STATUS_BAR                     0x1E801
#define HID_RECORD_FIRST                        0x1E900
#define HID_RECORD_LAST                         0x1E901
#define HID_RECORD_NEXT                         0x1E902
#define HID_RECORD_PREV                         0x1E903
#define HID_WIZBACK                             0x13023
#define HID_WIZNEXT                             0x13024
#define HID_WIZFINISH                           0x13025

// Dialogs (AFX_HIDD_*)
#define AFX_HIDD_FILEOPEN                       0x27004
#define AFX_HIDD_FILESAVE                       0x27005
#define AFX_HIDD_FONT                           0x27006
#define AFX_HIDD_COLOR                          0x27007
#define AFX_HIDD_PRINT                          0x27008
#define AFX_HIDD_PRINTSETUP                     0x27009
#define AFX_HIDD_FIND                           0x2700A
#define AFX_HIDD_REPLACE                        0x2700B
#define AFX_HIDD_NEWTYPEDLG                     0x27801
#define AFX_HIDD_PRINTDLG                       0x27802
#define AFX_HIDD_PREVIEW_TOOLBAR                0x27803
#define AFX_HIDD_PREVIEW_SHORTTOOLBAR           0x2780B
#define AFX_HIDD_INSERTOBJECT                   0x27804
#define AFX_HIDD_CHANGEICON                     0x27805
#define AFX_HIDD_CONVERT                        0x27806
#define AFX_HIDD_PASTESPECIAL                   0x27807
#define AFX_HIDD_EDITLINKS                      0x27808
#define AFX_HIDD_FILEBROWSE                     0x27809
#define AFX_HIDD_BUSY                           0x2780A
#define AFX_HIDD_OBJECTPROPERTIES               0x2780C
#define AFX_HIDD_CHANGESOURCE                   0x2780D

// Prompts/Errors (AFX_HIDP_*)
#define AFX_HIDP_NO_ERROR_AVAILABLE             0x3F020
#define AFX_HIDP_INVALID_FILENAME               0x3F100
#define AFX_HIDP_FAILED_TO_OPEN_DOC             0x3F101
#define AFX_HIDP_FAILED_TO_SAVE_DOC             0x3F102
#define AFX_HIDP_ASK_TO_SAVE                    0x3F103
#define AFX_HIDP_FAILED_TO_CREATE_DOC           0x3F104
#define AFX_HIDP_FILE_TOO_LARGE                 0x3F105
#define AFX_HIDP_FAILED_TO_START_PRINT          0x3F106
#define AFX_HIDP_FAILED_TO_LAUNCH_HELP          0x3F107
#define AFX_HIDP_INTERNAL_FAILURE               0x3F108
#define AFX_HIDP_COMMAND_FAILURE                0x3F109
#define AFX_HIDP_FAILED_MEMORY_ALLOC            0x3F10A
#define AFX_HIDP_UNREG_DONE                     0x3F10B
#define AFX_HIDP_UNREG_FAILURE                  0x3F10C
#define AFX_HIDP_DLL_LOAD_FAILED                0x3F10D
#define AFX_HIDP_DLL_BAD_VERSION                0x3F10E
#define AFX_HIDP_PARSE_INT                      0x3F110
#define AFX_HIDP_PARSE_REAL                     0x3F111
#define AFX_HIDP_PARSE_INT_RANGE                0x3F112
#define AFX_HIDP_PARSE_REAL_RANGE               0x3F113
#define AFX_HIDP_PARSE_STRING_SIZE              0x3F114
#define AFX_HIDP_PARSE_RADIO_BUTTON             0x3F115
#define AFX_HIDP_PARSE_BYTE                     0x3F116
#define AFX_HIDP_PARSE_UINT                     0x3F117
#define AFX_HIDP_PARSE_DATETIME                 0x3F118
#define AFX_HIDP_PARSE_CURRENCY                 0x3F119
#define AFX_HIDP_FAILED_INVALID_FORMAT          0x3F120
#define AFX_HIDP_FAILED_INVALID_PATH            0x3F121
#define AFX_HIDP_FAILED_DISK_FULL               0x3F122
#define AFX_HIDP_FAILED_ACCESS_READ             0x3F123
#define AFX_HIDP_FAILED_ACCESS_WRITE            0x3F124
#define AFX_HIDP_FAILED_IO_ERROR_READ           0x3F125
#define AFX_HIDP_FAILED_IO_ERROR_WRITE          0x3F126
#define AFX_HIDP_STATIC_OBJECT                  0x3F180
#define AFX_HIDP_FAILED_TO_CONNECT              0x3F181
#define AFX_HIDP_SERVER_BUSY                    0x3F182
#define AFX_HIDP_BAD_VERB                       0x3F183
#define AFX_HIDP_FAILED_TO_NOTIFY               0x3F185
#define AFX_HIDP_FAILED_TO_LAUNCH               0x3F186
#define AFX_HIDP_ASK_TO_UPDATE                  0x3F187
#define AFX_HIDP_FAILED_TO_UPDATE               0x3F188
#define AFX_HIDP_FAILED_TO_REGISTER             0x3F189
#define AFX_HIDP_FAILED_TO_AUTO_REGISTER        0x3F18A
#define AFX_HIDP_FAILED_TO_CONVERT              0x3F18B
#define AFX_HIDP_GET_NOT_SUPPORTED              0x3F18C
#define AFX_HIDP_SET_NOT_SUPPORTED              0x3F18D
#define AFX_HIDP_ASK_TO_DISCARD                 0x3F18E
#define AFX_HIDP_FAILED_TO_CREATE               0x3F18F
#define AFX_HIDP_FAILED_MAPI_LOAD               0x3F190
#define AFX_HIDP_INVALID_MAPI_DLL               0x3F191
#define AFX_HIDP_FAILED_MAPI_SEND               0x3F192
#define AFX_HIDP_FILE_NONE                      0x3F1A0
#define AFX_HIDP_FILE_GENERIC                   0x3F1A1
#define AFX_HIDP_FILE_NOT_FOUND                 0x3F1A2
#define AFX_HIDP_FILE_BAD_PATH                  0x3F1A3
#define AFX_HIDP_FILE_TOO_MANY_OPEN             0x3F1A4
#define AFX_HIDP_FILE_ACCESS_DENIED             0x3F1A5
#define AFX_HIDP_FILE_INVALID_FILE              0x3F1A6
#define AFX_HIDP_FILE_REMOVE_CURRENT            0x3F1A7
#define AFX_HIDP_FILE_DIR_FULL                  0x3F1A8
#define AFX_HIDP_FILE_BAD_SEEK                  0x3F1A9
#define AFX_HIDP_FILE_HARD_IO                   0x3F1AA
#define AFX_HIDP_FILE_SHARING                   0x3F1AB
#define AFX_HIDP_FILE_LOCKING                   0x3F1AC
#define AFX_HIDP_FILE_DISKFULL                  0x3F1AD
#define AFX_HIDP_FILE_EOF                       0x3F1AE
#define AFX_HIDP_ARCH_NONE                      0x3F1B0
#define AFX_HIDP_ARCH_GENERIC                   0x3F1B1
#define AFX_HIDP_ARCH_READONLY                  0x3F1B2
#define AFX_HIDP_ARCH_ENDOFFILE                 0x3F1B3
#define AFX_HIDP_ARCH_WRITEONLY                 0x3F1B4
#define AFX_HIDP_ARCH_BADINDEX                  0x3F1B5
#define AFX_HIDP_ARCH_BADCLASS                  0x3F1B6
#define AFX_HIDP_ARCH_BADSCHEMA                 0x3F1B7
#define AFX_HIDP_SQL_CONNECT_FAIL               0x3F281
#define AFX_HIDP_SQL_RECORDSET_FORWARD_ONLY     0x3F282
#define AFX_HIDP_SQL_EMPTY_COLUMN_LIST          0x3F283
#define AFX_HIDP_SQL_FIELD_SCHEMA_MISMATCH      0x3F284
#define AFX_HIDP_SQL_ILLEGAL_MODE               0x3F285
#define AFX_HIDP_SQL_MULTIPLE_ROWS_AFFECTED     0x3F286
#define AFX_HIDP_SQL_NO_CURRENT_RECORD          0x3F287
#define AFX_HIDP_SQL_NO_ROWS_AFFECTED           0x3F288
#define AFX_HIDP_SQL_RECORDSET_READONLY         0x3F289
#define AFX_HIDP_SQL_SQL_NO_TOTAL               0x3F28A
#define AFX_HIDP_SQL_ODBC_LOAD_FAILED           0x3F28B
#define AFX_HIDP_SQL_DYNASET_NOT_SUPPORTED      0x3F28C
#define AFX_HIDP_SQL_SNAPSHOT_NOT_SUPPORTED     0x3F28D
#define AFX_HIDP_SQL_API_CONFORMANCE            0x3F28E
#define AFX_HIDP_SQL_SQL_CONFORMANCE            0x3F28F
#define AFX_HIDP_SQL_NO_DATA_FOUND              0x3F290
#define AFX_HIDP_SQL_ROW_UPDATE_NOT_SUPPORTED   0x3F291
#define AFX_HIDP_SQL_ODBC_V2_REQUIRED           0x3F292
#define AFX_HIDP_SQL_NO_POSITIONED_UPDATES      0x3F293
#define AFX_HIDP_SQL_LOCK_MODE_NOT_SUPPORTED    0x3F294
#define AFX_HIDP_SQL_DATA_TRUNCATED             0x3F295
#define AFX_HIDP_SQL_ROW_FETCH                  0x3F296
#define AFX_HIDP_SQL_INCORRECT_ODBC             0x3F297
#define AFX_HIDP_SQL_UPDATE_DELETE_FAILED       0x3F298
#define AFX_HIDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED	0x3F299
#define AFX_HIDP_SQL_FIELD_NOT_FOUND            0x3F29A
#define AFX_HIDP_SQL_BOOKMARKS_NOT_SUPPORTED    0x3F29B
#define AFX_HIDP_SQL_BOOKMARKS_NOT_ENABLED      0x3F29C
#define AFX_HIDP_DAO_ENGINE_INITIALIZATION      0x3F2B0
#define AFX_HIDP_DAO_DFX_BIND                   0x3F2B1
#define AFX_HIDP_DAO_OBJECT_NOT_OPEN            0x3F2B2
#define AFX_HIDP_DAO_ROWTOOSHORT                0x3F2B3
#define AFX_HIDP_DAO_BADBINDINFO                0x3F2B4
#define AFX_HIDP_DAO_COLUMNUNAVAILABLE          0x3F2B5

// Frame Controls (AFX_HIDW_*)
#define AFX_HIDW_TOOLBAR                        0x5E800
#define AFX_HIDW_STATUS_BAR                     0x5E801
#define AFX_HIDW_PREVIEW_BAR                    0x5E802
#define AFX_HIDW_RESIZE_BAR                     0x5E803
#define AFX_HIDW_DOCKBAR_TOP                    0x5E81B
#define AFX_HIDW_DOCKBAR_LEFT                   0x5E81C
#define AFX_HIDW_DOCKBAR_RIGHT                  0x5E81D
#define AFX_HIDW_DOCKBAR_BOTTOM                 0x5E81E
#define AFX_HIDW_DOCKBAR_FLOAT                  0x5E81F

/////////////////////////////////////////////////////////////////////////////
